site_name: Fada
repo_url: https://github.com/clinical-genomics-uppsala/fada
nav:
  - Overview:
    - Introduction: index.md
    - Usage Guide: usage.md
    - Workflows:
      - PacBio Twist Cancer: pb_twist_cancer.md
      - PacBio WGS: pb_wgs.md
      - ONT STR: ont_str.md
  - Development:
    - Documentation: documentation.md
  - Pipeline specific rules:
    - Rule list: softwares.md
  

theme:
    name: material
    palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css: [extra.css]
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - mdx_spanner
  - pymdownx.blocks.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path: "docs/"
      url_download: "True"
  - pymdownx.emoji
  - toc:
      permalink: True

plugins:
  - include-markdown
  - search
  - macros:
      module_name: docs/main
  - yaml-schema:
      yaml_files:
        - file: "workflow/schemas/config.schema.yaml"
          tag: "CONFIGSCHEMA"
        - file: "workflow/schemas/resources.schema.yaml"
          tag: "RESOURCESSCHEMA"
  - snakemake-rule:
      rule_folders:
        - 'workflow/rules'
      schemas:
        - 'workflow/schemas/rules.schema.yaml'
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.hooks:copy_changelog_and_license"