---

PIPELINE_REF_DATA: "/data/ref_data/wp3/fada/GRCH38"

default_container: "docker://hydragenetics/common:1.11.1"

resources: "config/resources.yaml"

modules:
  alignment: "1f4bc73"
  annotation: "3ce9da5"
  compression: "b3ef8cc"
  cnv_sv: "v0.6.0"
  # filtering: "v0.3.0"
  qc: "6bb90bb"
  misc: "cd1e891"
  snv_indels: "0ed8526"

reference:
  design_bed: ""
  fasta: "{{PIPELINE_REF_DATA}}/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta"
  fai: "{{PIPELINE_REF_DATA}}/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta.fai"
  pathogenic_repeats_bed: "{{PIPELINE_REF_DATA}}/pathogenic_repeats.hg38.bed"

multiqc:
  container: "docker://hydragenetics/multiqc:1.21"
  reports:
    DNA:
      config: "config/multiqc_config_DNA.yaml"
      included_unit_types: ["N"]
      qc_files:
        - "qc/mosdepth/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth/{sample}_{type}.mosdepth.global.dist.txt"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
        - "qc/samtools_idxstats/{sample}_{type}.samtools-idxstats.txt"

mosdepth:
  container: "docker://hydragenetics/mosdepth:0.3.2"

