---
output: "config/output_pacbio_wgs.yaml"
samples: "samples_pacbio_wgs.tsv"
units: "units_pacbio_wgs.tsv"

aligner: "pbmm2"

deepvariant:
  container: "docker://google/deepvariant:1.6.1"
  model_type: "PACBIO"
  output_gvcf: false

pbmm2_index:
  preset: "HIFI"
  container: "docker://hydragenetics/pbmm2:1.10"

pbmm2_align:
  preset: "HIFI"
  container: "docker://hydragenetics/pbmm2:1.10"
  extra: "--unmapped "

minimap2_align:
  container: "docker://hydragenetics/minimap2:2.26"
  preset: "map-hifi"

mosdepth:
  by: "500"
  extra: "--fast-mode --use-median --no-per-base "

trgt_genotype:
  container: "docker://hydragenetics/trgt:1.0.0"
  bed: "{{PIPELINE_REF_DATA}}/pathogenic_repeats.hg38.bed"

trgt_plot_motifs:
  container: "docker://hydragenetics/trgt:1.0.0"
  image_type: "svg"
  plot_type: "allele"
  show: "motifs"

trgt_plot_meth:
  image_type: "svg"
  plot_type: "allele"
  show: "meth"
  container: "docker://hydragenetics/trgt:1.0.0"

sniffles2_call:
  container: "docker://hydragenetics/sniffles2:2.4"
  bed: "{{PIPELINE_REF_DATA}}/pathogenic_repeats.hg38.bed"

stranger:
  catalog: "{{PIPELINE_REF_DATA}}/variant_catalog_hg38.json"
  container: "docker://hydragenetics/stranger:0.9.1"
  extra: "--trgt"

