---

PIPELINE_REF_DATA: "/data/ref_data/wp3/fada/GRCH38"

default_container: "docker://hydragenetics/common:3.1.1"

resources: "config/resources.yaml"

modules:
  alignment: "v0.7.0"
  annotation: "283944d"
  compression: "v2.1.0"
  cnv_sv: "990acf6"
  filtering: "v1.1.0"
  misc: "v0.3.0"
  prealignment: "v1.4.0"
  qc: "v0.6.0"
  snv_indels: "v1.2.0"

reference:
  fasta: "{{PIPELINE_REF_DATA}}/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta"
  fai: "{{PIPELINE_REF_DATA}}/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.fai"
  pathogenic_repeats_bed: "{{PIPELINE_REF_DATA}}/pathogenic_repeats.hg38.bed"

minimap2_index:
  container: "docker://hydragenetics/minimap2:2.26"

minimap2_align:
  container: "docker://hydragenetics/minimap2:2.26"

cramino:
  container: "docker://hydragenetics/cramino:0.14.5"

multiqc:
  container: "docker://hydragenetics/multiqc:1.27.1"

nanoplot:
  container: "docker://hydragenetics/nanoplot:1.44.1"

sequali:
  container: "docker://hydragenetics/sequali:0.12.0"
