---
output: "config/output_pacbio_wgs.yaml"
samples: "samples_pacbio_wgs.tsv"
units: "units_pacbio_wgs.tsv"

aligner: "pbmm2"

deepvariant:
  container: "docker://google/deepvariant:1.6.1"
  model_type: "PACBIO"
  output_gvcf: false

pbmm2_index:
  preset: "HIFI"
  container: "docker://hydragenetics/pbmm2:1.10"

pbmm2_align:
  preset: "HIFI"
  container: "docker://hydragenetics/pbmm2:1.10"
  extra: "--unmapped "

minimap2_align:
  preset: "map-hifi"

mosdepth:
  container: "docker://hydragenetics/mosdepth:0.3.2"
  by: "500"
  extra: "--fast-mode --use-median --no-per-base "

trgt_genotype:
  bed: "{{PIPELINE_REF_DATA}}/pathogenic_repeats.hg38.bed"
  container: "docker://hydragenetics/trgt:1.0.0"

trgt_plot_motifs:
  image_type: "svg"
  plot_type: "allele"
  show: "motifs"
  container: "docker://hydragenetics/trgt:1.0.0"

trgt_plot_meth:
  image_type: "svg"
  plot_type: "allele"
  show: "meth"
  container: "docker://hydragenetics/trgt:1.0.0"

stranger:
  extra: "--trgt"
