---

PIPELINE_REF_DATA: "/data/ref_data/wp3/fada/GRCH38"

default_container: "docker://hydragenetics/common:3.1.1"

resources: "config/resources.yaml"

modules:
  alignment: "5444def"
  annotation: "3ce9da5"
  compression: "b3ef8cc"
  cnv_sv: "7f236b9"
  filtering: "be5cc98"
  misc: "cd1e891"
  prealignment: "85b0fc5"
  qc: "911c879"
  snv_indels: "fc7673a"

reference:
  fasta: "{{PIPELINE_REF_DATA}}/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta"
  fai: "{{PIPELINE_REF_DATA}}/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta.fai"
  pathogenic_repeats_bed: "{{PIPELINE_REF_DATA}}/pathogenic_repeats.hg38.bed"

minimap2_index:
  container: "docker://hydragenetics/minimap2:2.26"

minimap2_align:
  container: "docker://hydragenetics/minimap2:2.26"

cramino:
  container: "docker://hydragenetics/cramino:0.14.5"

multiqc:
  container: "docker://hydragenetics/multiqc:1.27.1"

nanoplot:
  container: "docker://hydragenetics/nanoplot:1.44.1"

sequali:
  container: "docker://hydragenetics/sequali:0.12.0"
