---

PIPELINE_REF_DATA: "/data/ref_data/wp3/fada/GRCH38"

default_container: "docker://hydragenetics/common:1.11.1"

resources: "config/resources.yaml"

modules:
  alignment: "45c5346"
  annotation: "3ce9da5"
  compression: "b3ef8cc"
  cnv_sv: "75bc154"
  # filtering: "v0.3.0"
  misc: "cd1e891"
  prealignment: "501fd6b"
  qc: "6bb90bb"
  snv_indels: "2fa0c4e"


reference:
  fasta: "{{PIPELINE_REF_DATA}}/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta"
  fai: "{{PIPELINE_REF_DATA}}/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta.fai"
  pathogenic_repeats_bed: "{{PIPELINE_REF_DATA}}/pathogenic_repeats.hg38.bed"



