---
pipeline: "pacbio_wgs"
output: "config/output_pacbio_wgs.yaml"
samples: "samples_pacbio_wgs.tsv"
units: "units_pacbio_wgs.tsv"

aligner: "pbmm2"
phaser: "hiphase"
trimmer_software: None


reference:
  skip_contigs: #scaffolds in hg38 to skip in deepvariant calling
    - ".*_random"
    - "chrUn_.*"
    - "chrEBV"
    - "^MAP2K3_.*"
    - "^KCNJ18_.*"
    - "^KMT2C_.*"

reference:
  design_bed: ""

deepvariant:
  container: "docker://google/deepvariant:1.8.0"
  model_type: "PACBIO"
  output_gvcf: false

pbmm2_index:
  preset: "HIFI"
  container: "docker://hydragenetics/pbmm2:1.16"

pbmm2_align:
  preset: "HIFI"
  container: "docker://hydragenetics/pbmm2:1.16"
  extra: "--unmapped "

minimap2_align:
  container: "docker://hydragenetics/minimap2:2.26"
  preset: "map-hifi"
  extra: "-Y --secondary=no "

mosdepth:
  container: "docker://hydragenetics/mosdepth:0.3.2"
  by: "500"
  extra: "--fast-mode --use-median --no-per-base "

multiqc:
  container: "docker://hydragenetics/multiqc:1.25.1"
  reports:
    pacbio_wgs:
      config: "config/multiqc_config_pacbio_wgs.yaml"
      included_unit_types: ["N"]
      qc_files:
        - "qc/mosdepth/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth/{sample}_{type}.mosdepth.global.dist.txt"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
        - "qc/samtools_idxstats/{sample}_{type}.samtools-idxstats.txt"

paraphase:
  container: "docker://quay.io/pacbio/paraphase:3.2.1_build1"
  genome: "38"
  extra: ""
  genes:
    - pms2

trgt_genotype:
  container: "docker://hydragenetics/trgt:1.0.0"
  bed: "{{PIPELINE_REF_DATA}}/pathogenic_repeats.hg38.bed"

trgt_plot:
  container: "docker://hydragenetics/trgt:1.0.0"

trgt_plot_motifs:
  image_type: "svg"
  plot_type: "allele"
  show: "motifs"

trgt_plot_meth:
  image_type: "svg"
  plot_type: "allele"
  show: "meth"

sniffles2_call:
  container: "docker://hydragenetics/sniffles2:2.6.1"
  bed: "{{PIPELINE_REF_DATA}}/pathogenic_repeats.hg38.bed"

stranger:
  catalog: "{{PIPELINE_REF_DATA}}/variant_catalog_hg38.json"
  container: "docker://hydragenetics/stranger:0.9.1"
  extra: "--trgt"

