---
files: 
    # Cram files
  - name: "samtools_cram"
    output: "results/{sample}/cram/{sample}.cram"
    input: "compression/samtools_view/{sample}_N.cram"
  - name: "samtools_crai"
    output: "results/{sample}/cram/{sample}.cram.crai"
    input: "compression/samtools_view/{sample}_N.cram.crai"

    #SNV & INDEL files
  - name: "deepvariant_phased_vcf"
    output: "results/{sample}/snv_indels/{sample}.deepvariant.phased.vcf.gz"
    input: "snv_indels/hiphase/{sample}_N.deepvariant.phased.vcf.gz"
  - name: "deepvariant_phased_tbi"
    output: "results/{sample}/snv_indels/{sample}.deepvariant.phased.vcf.gz.tbi"
    input: "snv_indels/hiphase/{sample}_N.deepvariant.phased.vcf.gz.tbi"
  
    # CNV & SV files
  - name: "pbsv_vcf"
    output: "results/{sample}/cnv_sv/{sample}.pbsv.vcf.gz"
    input: "cnv_sv/pbsv_call/{sample}_N_GRCh38.vcf.gz"
  - name: "pbsv_vcf_tbi"
    output: "results/{sample}/cnv_sv/{sample}.pbsv.vcf.gz.tbi"
    input: "cnv_sv/pbsv_call/{sample}_N_GRCh38.vcf.gz.tbi"
  
  - name: "sawfish_vcf"
    output: "results/{sample}/cnv_sv/{sample}.sawfish.vcf.gz"
    input: "cnv_sv/sawfish_joint_call_single/{sample}_N.vcf.gz"
  - name: "sawfish_vcf_tbi"
    output: "results/{sample}/cnv_sv/{sample}.sawfish.vcf.gz.tbi"
    input: "cnv_sv/sawfish_joint_call_single/{sample}_N.vcf.gz.tbi"

  - name: "sniffles2_vcf"
    output: "results/{sample}/cnv_sv/{sample}.sniffles2.vcf.gz"
    input: "cnv_sv/sniffles2_call/{sample}_N_GRCh38.vcf.gz"
  - name: "sniffles2_vcf_tbi"
    output: "results/{sample}/cnv_sv/{sample}.sniffles2.vcf.gz.tbi"
    input: "cnv_sv/sniffles2_call/{sample}_N_GRCh38.vcf.gz.tbi"
  
  - name: "paraphase_bam"
    output: "results/{sample}/paraphase/{sample}.paraphase.bam"
    input: "cnv_sv/paraphase/paraphase_{sample}_N/{sample}_N.paraphase.bam"
  - name: "paraphase_bai"
    output: "results/{sample}/paraphase/{sample}.paraphase.bam.bai"
    input: "cnv_sv/paraphase/paraphase_{sample}_N/{sample}_N.paraphase.bam.bai"
  - name: "paraphase_json"
    output: "results/{sample}/paraphase/{sample}.paraphase.json"
    input: "cnv_sv/paraphase/paraphase_{sample}_N/{sample}_N.paraphase.json"
  - name: "paraphase_vcf"
    output: "results/{sample}/paraphase/{sample}.paraphase.{gene}.vcf.gz"
    input: "cnv_sv/paraphase/paraphase_{sample}_N/{sample}_N_paraphase_vcfs/{sample}_N_{gene}_GRCh38.vcf.gz"
  - name: "paraphase_vcf_tbi"
    output: "results/{sample}/paraphase/{sample}.paraphase.{gene}.vcf.gz.tbi"
    input: "cnv_sv/paraphase/paraphase_{sample}_N/{sample}_N_paraphase_vcfs/{sample}_N_{gene}_GRCh38.vcf.gz.tbi"


    # Repeat expansion files
  - name: "stranger_trgt_vcf"
    output: "results/{sample}/repeat_expansions/{sample}.trgt.vcf.gz"
    input: "annotation/stranger/{sample}_N.trgt.vcf.gz"
  # - name: "stranger_trgt_tbi"
  #   output: "results/{sample}/repeat_expansions/{sample}.trgt.vcf.gz.tbi"
  #   input: "annotation/stranger/{sample}_N.trgt.vcf.gz.tbi"

  - name: "trgt_plot_motif"
    output: "results/{sample}/repeat_expansions/trgt_plot/motif/{sample}_{locus}.{suffix}"
    input: "cnv_sv/trgt_plot/motif/{sample}_N_{locus}.{suffix}"
  - name: "trgt_plot_meth"
    output: "results/{sample}/repeat_expansions/trgt_plot/meth/{sample}_{locus}.{suffix}"
    input: "cnv_sv/trgt_plot/meth/{sample}_N_{locus}.{suffix}"
  
  # QC files
  - name: "multiqc_report"
    output: "results/multiqc_pacbio_wgs.html"
    input: "qc/multiqc/multiqc_pacbio_wgs.html"
