---
files: 
    # Cram files
  - name: "samtools_cram"
    output: "results/{sample}/cram/{sample}.cram"
    input: "compression/samtools_view/{sample}_N.cram"
  - name: "samtools_crai"
    output: "results/{sample}/cram/{sample}.cram.crai"
    input: "compression/samtools_view/{sample}_N.cram.crai"

  # QC files
  - name: "multiqc_report"
    output: "results/multiqc_DNA.html"
    input: "qc/multiqc/multiqc_DNA.html"
  - name: "mosdepth_bed_design_regions_bed_gz"
    output: "results/{sample}/mosdepth_bed_design/{sample}.mosdepth.regions.bed.gz"
    input: "qc/mosdepth_bed_design/{sample}_N.regions.bed.gz"
  - name: "mosdepth_bed_design_regions_bed_gz_csi"
    output: "results/{sample}/mosdepth_bed_design/{sample}.mosdepth.regions.bed.gz.csi"
    input: "qc/mosdepth_bed_design/{sample}_N.regions.bed.gz.csi"
  - name: "mosdepth_bed_design_per_base_bed_gz"
    output: "results/{sample}/mosdepth_bed_design/{sample}.mosdepth.per-base.bed.gz"
    input: "qc/mosdepth_bed_design/{sample}_N.per-base.bed.gz"
  - name: "mosdepth_bed_design_per_base_bed_gz_csi"
    output: "results/{sample}/mosdepth_bed_design/{sample}.mosdepth.per-base.bed.gz.csi"
    input: "qc/mosdepth_bed_design/{sample}_N.per-base.bed.gz.csi"
  - name: "mosdepth_bed_design_mosdepth_global_dist_txt"
    output: "results/{sample}/mosdepth_bed_design/{sample}.mosdepth.global.dist.txt"
    input: "qc/mosdepth_bed_design/{sample}_N.mosdepth.global.dist.txt"
  - name: "mosdepth_bed_design_mosdepth_region_dist_txt"
    output: "results/{sample}/mosdepth_bed_design/{sample}.mosdepth.region.dist.txt"
    input: "qc/mosdepth_bed_design/{sample}_N.mosdepth.region.dist.txt"
  - name: "mosdepth_bed_design_mosdepth_summary_txt"
    output: "results/{sample}/mosdepth_bed_design/{sample}.mosdepth.summary.txt"
    input: "qc/mosdepth_bed_design/{sample}_N.mosdepth.summary.txt"

  - name: "mosdepth_bed_str_regions_bed_gz"
    output: "results/{sample}/mosdepth_bed_str/{sample}.mosdepth.regions.bed.gz"
    input: "qc/mosdepth_bed_str/{sample}_N.regions.bed.gz"
  - name: "mosdepth_bed_str_regions_bed_gz_csi"
    output: "results/{sample}/mosdepth_bed_str/{sample}.mosdepth.regions.bed.gz.csi"
    input: "qc/mosdepth_bed_str/{sample}_N.regions.bed.gz.csi"
  - name: "mosdepth_bed_str_per_base_bed_gz"
    output: "results/{sample}/mosdepth_bed_str/{sample}.mosdepth.per-base.bed.gz"
    input: "qc/mosdepth_bed_str/{sample}_N.per-base.bed.gz"
  - name: "mosdepth_bed_str_per_base_bed_gz_csi"
    output: "results/{sample}/mosdepth_bed_str/{sample}.mosdepth.per-base.bed.gz.csi"
    input: "qc/mosdepth_bed_str/{sample}_N.per-base.bed.gz.csi"
  - name: "mosdepth_bed_str_mosdepth_global_dist_txt"
    output: "results/{sample}/mosdepth_bed_str/{sample}.mosdepth.global.dist.txt"
    input: "qc/mosdepth_bed_str/{sample}_N.mosdepth.global.dist.txt"
  - name: "mosdepth_bed_str_mosdepth_region_dist_txt"
    output: "results/{sample}/mosdepth_bed_str/{sample}.mosdepth.region.dist.txt"
    input: "qc/mosdepth_bed_str/{sample}_N.mosdepth.region.dist.txt"
  - name: "mosdepth_bed_str_mosdepth_summary_txt"
    output: "results/{sample}/mosdepth_bed_str/{sample}.mosdepth.summary.txt"
    input: "qc/mosdepth_bed_str/{sample}_N.mosdepth.summary.txt"


  #STRs
  - name: "strdust_vcf"
    output: "results/{sample}/STRs/{sample}.strdust.vcf"
    input: "cnv_sv/strdust/{sample}_N.vcf"
  - name: "strkit_vcf"
    output: "results/{sample}/STRs/{sample}.strkit.vcf"
    input: "cnv_sv/strkit_call/{sample}_N.vcf"

  

