---
files: 
    # Cram files
  - name: "samtools_cram"
    output: "results/{sample}.cram"
    input: "compression/samtools_view/{sample}_N.cram"
  - name: "samtools_crai"
    output: "results/{sample}.cram.crai"
    input: "compression/samtools_view/{sample}_N.cram.crai"

    #SNV & INDEL files
  - name: "deepvariant_vcf"
    output: "results/{sample}.deepvariant.vcf.gz."
    input: "snv_indels/deepvariant/{sample}_N.merged.vcf.gz"
  - name: "deepvariant_tbi"
    output: "results/{sample}.deepvariant.vcf.gz.tbi"
    input: "snv_indels/deepvariant/{sample}_N.merged.vcf.gz.tbi"

  # Repeat expansion files
  - name: "stranger_trgt_vcf"
    output: "results/{sample}.trgt.vcf.gz"
    input: "annotation/stranger/{sample}_N.trgt.vcf.gz"
  - name: "stranger_trgt_tbi"
    output: "results/{sample}.trgt.vcf.gz.tbi"
    input: "annotation/stranger/{sample}_N.trgt.vcf.gz.tbi"
