---
files: 
      # Cram files
  - name: "samtools_cram"
    output: "results/{sample}/cram/{sample}.cram"
    input: "compression/samtools_view/{sample}_N.cram"
  - name: "samtools_crai"
    output: "results/{sample}/cram/{sample}.cram.crai"
    input: "compression/samtools_view/{sample}_N.cram.crai"

  # QC files
  - name: "multiqc_report"
    output: "results/multiqc_DNA.html"
    input: "qc/multiqc/multiqc_DNA.html"
  # - name: "on_target_bai"
  #   output: "results/{sample}/{sample}.on_target.bam.bai"
  #   input: "qc/samtools_view_on_target/{sample}_N.on_target.bam.bai"
  - name: "on_target_tsv"
    output: "results/{sample}/{sample}.reads.on_target.tsv"
    input: "qc/samtools_view_on_target/{sample}_N.reads.on_target.tsv"
  # - name: "off_target_bai"
  #   output: "results/{sample}/{sample}.off_target.bam.bai"
  #   input: "qc/samtools_view_off_target/{sample}_N.off_target.bam.bai"
  - name: "mosdepth_bed_design_regions_bed_gz"
    output: "results/{sample}/{sample}.mosdepth.regions.bed.gz"
    input: "qc/mosdepth_bed_design/{sample}_N.regions.bed.gz"
  - name: "mosdepth_bed_design_regions_bed_gz_csi"
    output: "results/{sample}/{sample}.mosdepth.regions.bed.gz.csi"
    input: "qc/mosdepth_bed_design/{sample}_N.regions.bed.gz.csi"
  - name: "mosdepth_bed_design_per_base_bed_gz"
    output: "results/{sample}/{sample}.mosdepth.per-base.bed.gz"
    input: "qc/mosdepth_bed_design/{sample}_N.per-base.bed.gz"
  - name: "mosdepth_bed_design_per_base_bed_gz_csi"
    output: "results/{sample}/{sample}.mosdepth.per-base.bed.gz.csi"
    input: "qc/mosdepth_bed_design/{sample}_N.per-base.bed.gz.csi"
  - name: "mosdepth_bed_design_mosdepth_global_dist_txt"
    output: "results/{sample}/{sample}.mosdepth.global.dist.txt"
    input: "qc/mosdepth_bed_design/{sample}_N.mosdepth.global.dist.txt"
  - name: "mosdepth_bed_design_mosdepth_region_dist_txt"
    output: "results/{sample}/{sample}.mosdepth.region.dist.txt"
    input: "qc/mosdepth_bed_design/{sample}_N.mosdepth.region.dist.txt"
  - name: "mosdepth_bed_design_mosdepth_summary_txt"
    output: "results/{sample}/{sample}.mosdepth.summary.txt"
    input: "qc/mosdepth_bed_design/{sample}_N.mosdepth.summary.txt"


  # snv indels

