$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  output:
    type: string
    description: output yaml/json file defining expected output from pipeline
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container



# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  picard_bed_to_interval_list:
    type: object
    description: parameters for picard_bed_to_interval_list
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded



# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  picard_create_sequence_dictionary:
    type: object
    description: parameters for picard_create_sequence_dictionary
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded



# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  export_qc_bedtools_intersect:
    type: object
    description: parameters for export_qc_bedtools_intersect
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded



# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  export_qc_bedtools_intersect:
    type: object
    description: parameters for export_qc_bedtools_intersect
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded



# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  export_qc_bedtools_intersect_pgrs:
    type: object
    description: parameters for export_qc_bedtools_intersect_pgrs
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded



# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  export_qc_xlsx_report:
    type: object
    description: parameters for export_qc_xlsx_report
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

required:
  - samples
  - units
  - output
  - resources
  - default_container

