name: small integration test

# Controls when the action will run.
on:
   # Triggers the workflow on push or pull request events but only for the master and develop branch
  push:
    branches:
     - develop
     - main
  pull_request:
    branches:
     - develop
     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
   integration-small-singularity:
    name: integration small data set singularity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Build
        run: |
          echo "Free space:"
          df -h
      - name: Remove stuff
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
      - name: Build
        run: |
          echo "Free space:"
          df -h
      - name: Install apptainer/singularity
        run: |
          sudo add-apt-repository -y ppa:apptainer/ppa && sudo apt install -y software-properties-common && sudo apt install -y apptainer-suid
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Integration test - small dataset twist cancer
        working-directory: .tests/integration
        run: |
          mkdir singularity_files && cp -r ../../config . && snakemake -s ../../workflow/Snakefile -j 2 -p --show-failed-logs --configfiles config/config.yaml config/config_pacbio_twist_cancer.yaml --config resources=resources_test.yaml PIPELINE_REF_DATA=reference sequenceid="test"  lima_reports=lima_reports/ --use-singularity  --singularity-args  " --no-home --cleanenv --bind /home/runner " --singularity-prefix singularity_files 
      
