name: Snakemake dry run

on:
  push:
    branches:
     - develop
     - main
  pull_request:
    branches:
     - develop
     - main
  workflow_dispatch:

jobs:
  snakemake-dry-run:
    name: Run snakemake dry run 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: snakemake dry run pacbio wgs
        working-directory: .tests/integration
        run: |
          cp -r ../../config . && snakemake -n -s ../../workflow/Snakefile --configfiles config/config.yaml config/config_pacbio_wgs.yaml --config PIPELINE_REF_DATA=reference
      - name: snakemake dry run pacbio twist cancer
        working-directory: .tests/integration
        run: |
          cp -r ../../config . && snakemake -n -s ../../workflow/Snakefile --configfiles config/config.yaml config/config_pacbio_twist_cancer.yaml --config PIPELINE_REF_DATA=reference sequenceid="test"
      - name: snakemake dry run ont targeted str
        working-directory: .tests/integration
        run: |
          cp -r ../../config . && snakemake -n -s ../../workflow/Snakefile --configfiles config/config.yaml config/config_ont_target_str.yaml --config PIPELINE_REF_DATA=reference
